version: '3.8'

services:
   # Telegram bot and admin panel service
   image_detection_bot:
     build: .
     container_name: image_detection_bot
     restart: always
     volumes:
       - /root/image_detection_bot/logs:/usr/src/app/image_detection_bot/logs  # Mount volume for storing logs
       